nodeLinker: node-modules
networkTimeout: 100000
enableGlobalCache: true
enableScripts: true
enableTelemetry: false
unsafeHttpWhitelist:
  - "registry.npmjs.org"
private: true
workspaces-experimental: true 